name: ml-for-bem-full

channels:
  - pytorch
  - nvidia
  - plotly
  - conda-forge
dependencies:
  - pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda=11.8
  - ipywidgets
  - nbformat
  - plotly
  - numpy
  - python=3.8
  - requests
  - google-cloud-storage
  - h5py
  - pytables
  - shapely<2
  - geopandas<0.13
  - pandas<2
  - pip
  - pip:
    - archetypal
    - geomeppy
    - ladybug-core
    - python-dotenv
  
