name: ml-for-bem-final

channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pytorch 
  - pytorch-cuda=11.8
  - ipywidgets
  - nbformat
  - fiona
  - numpy
  - python=3.8
  - requests
  - google-cloud-storage
  - h5py
  - pytables
  - tensorboard
  - jsondiff
  - geopandas<0.13
  - pandas<2
  - shapely<2
  - pip
  - pip:
    - -r ../../pyumi/requirements.txt
    - ladybug-core
    - -e ../../pyumi 
    - -e ../../archetypal
    - geomeppy==0.11.8
    - pvlib
    - torchsummary
  
